
services:
  mssql-2022:
    container_name: devenv-mssql2k22
    build:
      context: .
      dockerfile: ./docker/mssql/Dockerfile
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
