
services:
  dev-postgres:
    container_name: dev-postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
        - ./vol/postgres:/var/lib/postgresql