
services:
  dev-mssql:
    container_name: dev-mssql
    build:
      context: .
      dockerfile: ./docker/mssql/Dockerfile
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
